### ISSUE TITLE
Data Center Compatible?

### ISSUE THREAD

**Issue by wayn3w** [OrbitzWorldwide/stash-permission-viewer-plugin#3]
Given its nature, it seems this plugin will work with Stash Data Center as-is.  Could you consider updating the pom so that it will be listed in the marketplace as Data Center ready, as in [Marking your plugin as cluster compatible for the Marketplace] (https://developer.atlassian.com/stash/docs/latest/how-tos/cluster-safe-plugins.html#Marking_your_plugin_as_cluster_compatible_for_the_Marketplace)

**Comment by cjcdoomed** [comment]
Sure can!  Check out version 1.2 in the marketplace!
